### ISSUE TITLE
Improve the Car Emulator Dummy data 

### ISSUE THREAD

**Issue by Nathanrs97** [sufst/intermediate-server#10]
### 1. Please describe the feature you are trying to request.
The car emulator should create more realistic dummy data for testing the front-end GUI application.
### 2. Describe the solution you'd like.
* Rather than just incrementing each data field value by 1 each transmission, each data field should have a more realistic output based on real-world value ranges of that data field.
* The dummy data values should also be randomised within bounds or follow a mathematical pattern such as a sine wave to exercise them.
* Logging of each data field transmitted would be useful to trace the values during testing..

**Comment by Nathanrs97** [comment]
Creating a new project to track the car emulator tasks separately from the intermediate server itself.

**Comment by Nathanrs97** [comment]
@przemekff Is the updated values in the pull request suitable to close this ticket?

**Comment by Nathanrs97** [comment]
Only the ACPDU values are left to be updated to reasonable dummy values. Currently, they are still incremental updates each transmits:
```
self._injection_time += 1
self._injection_duty_cycle += 1
self._lambda_pid_adjust += 1
self._lambda_pid_target += 1
self._advance += 1
```
Once these have been updated the ticket can be closed.

**Comment by Nathanrs97** [comment]
The best bet to update these dummy value is to review the ECU manual and identify the range of values these usually take from there. Otherwise, the old GUI had a range set for them so we can use that range as just create a sine wave or similar between those ranges.

**Comment by przemekff** [comment]
Do you know what appdu advance variable is ? It's not explained in the protocol wiki

**Comment by przemekff** [comment]
> 
> 
> Do you know what appdu advance variable is ? It's not explained in the protocol wiki

Nevermind, find out by myself.

For anyone wondering, here's wikipedia explanation:
`Mechanical ignition systems use a mechanical spark distributor to distribute a high voltage current to the correct spark plug at the correct time. In order to set an initial timing advance or timing retard for an engine, the engine is allowed to idle and the distributor is adjusted to achieve the best ignition timing for the engine at idle speed. This process is called 'setting the base advance'. There are two methods of increasing timing advance past the base advance. The advances achieved by these methods are added to the base advance number in order to achieve a total timing advance number. `

**Comment by Nathanrs97** [comment]
> Do you know what appdu advance variable is ? It's not explained in the protocol wiki

Yeah sorry, the meanings behind the engine parameters are out of scope for the telemetry protocol wiki page. It would be good to have these details under the DAQ GitHub page wiki (that needs to be created still at this time) then the telemetry protocol page can just reference them for the details.
